- name: demo on vars
  hosts: local
  connection: local
  vars:
    COURSE: "Devopos"
    TRAINER: "Sumanth"
    Duration: "120hrs"

  tasks:
  - name: print information
    vars:
      COURSE: "Devopos with Sumanth"

    debug:
      msg: "Hi, I am learning {{ COURSE }}, Trainer is {{ TRAINER }},Duration is {{ Duration }}"